[package]
name = "path_follower"
version = "0.1.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]
readme = "README.md"

[lib]
name = "internal"
path = "src/internal.rs"

[dependencies]
nalgebra = "*"
