[package]
name = "path-follower"
version = "0.1.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]
readme = "README.md"

[dependencies]
rtk-ins570-rs = { path = "../rtk-ins570-rs" }
pose-filter = { path = "../pose-filter" }
nalgebra = "*"
